#ifndef _FPSGAME_HUDANNOUNCE_H
#define _FPSGAME_HUDANNOUNCE_H

enum hudannounceeffects {
    HUD_STATIC_CENTER = 0,
    HUD_STATIC_LEFT,
    HUD_STATIC_RIGHT,
    HUD_STATIC_TOP,
    HUD_STATIC_BOTTOM,
    HUD_FADE_LEFT_RIGHT,
    HUD_FADE_RIGHT_LEFT,
    HUD_FADE_TOP_BOTTOM,
    HUD_FADE_BOTTOM_TOP,
    HUD_ZOOM_IN,
    HUD_ZOOM_OUT,
    HUD_BLINK_CENTER
};


#endif
